server:
  port: 8208

mybatis-plus:
  type-enums-package: hue.xgd.ttyx.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 192.168.137.128
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: CORRELATED  #发布确认模式，消息是否被成功发送到交换机
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual   #消费端手动确认

redis:
  host: localhost
  port: 6379
  database: 0
  timeout: 1800000
  password:
  lettuce:
    pool:
      max-active: 20 #最大连接数
      max-wait: -1    #最大阻塞等待时间(负数表示没限制)
      max-idle: 5    #最大空闲
      min-idle: 0     #最小空闲