server:
  port: 8206

mybatis-plus:
  type-enums-package: hue.xgd.ttyx.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shequ-user?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
redis:
  host: localhost
  port: 6379
  database: 0
  timeout: 1800000
  password:
  lettuce:
    pool:
      max-active: 20 #最大连接数
      max-wait: -1    #最大阻塞等待时间(负数表示没限制)
      max-idle: 5    #最大空闲
      min-idle: 0     #最小空闲
wx:
  open:
    # 小程序微信公众平台appId
    app_id: wx85f4b33513603bfc
    # 小程序微信公众平台api秘钥
    app_secret: f8349bacb2283105d4371d2b4e90c9dc